# Numpy

In [54]:
import numpy as np
import time

In [15]:
x = np.random.random(10000000)
x

array([0.3505492 , 0.47879427, 0.98460655, ..., 0.88296616, 0.81980433,
       0.70428173])

In [20]:
#Obtener promedio
#convencional python

start = time.time()
sum(x) / len(x)
print(time.time() - start)

1.1765766143798828


In [21]:
#Numpy
start = time.time()
np.mean(x)
print(time.time() - start)

0.017614364624023438


# Creation arrays whith Numpy


Python list

In [22]:
import numpy as np

In [25]:
x = np.array([4,5,6,7])
x

array([4, 5, 6, 7])

In [28]:
#shape
print(x.shape)

#type
print(type(x))

#dtype
print(x.dtype)

(4,)
<class 'numpy.ndarray'>
int32


In [30]:
x = np.array(['Hello','there'])
x
print(x.shape)
print(type(x))
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [32]:
y = np.array([3,4,5,'Hello'])
y
print(y.shape)
print(type(y))
print(y.dtype)

(4,)
<class 'numpy.ndarray'>
<U11


In [34]:
x =

(2, 3)
<class 'numpy.ndarray'>
int32


Numpy Functions

In [40]:
#zeros
x = np.zeros((3,4), dtype=int)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
<class 'numpy.ndarray'>
int32


In [42]:
#ones
x = np.ones((3,4), dtype=int)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
<class 'numpy.ndarray'>
int32


In [43]:
x = np.full((3,4),4)
print(x)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [44]:
#eye

x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
#diag
x = np.diag([7,8,9])
print(x)

[[7 0 0]
 [0 8 0]
 [0 0 9]]


In [49]:
#arange

x = np.arange(10)
print(x)

x = np.arange(4,10)
print(x)

x = np.arange(4,10,2)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 6 8]


In [51]:
#linspace

x = np.linspace(4,10,5)
print(x)

[ 4.   5.5  7.   8.5 10. ]


In [59]:
#random

x = np.random.random((2,3))
print(x)

[[0.46285657 0.21214668 0.9028812 ]
 [0.84437417 0.76065364 0.96914965]]


In [65]:
#randint
x = np.random.randint(2, 9, (3, 2))
print(x)

[[6 2]
 [7 2]
 [2 7]]


In [70]:
#reshape

y = np.reshape(x, (6,1))
print(y)

[[6]
 [2]
 [7]
 [2]
 [2]
 [7]]


# Slicing

In [71]:
import numpy as np

In [73]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [82]:
z = x[0:1]
print(z)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [86]:
z = x[0:2, 0:4]
print(z)

[[0 1 2 3]
 [5 6 7 8]]


In [87]:
z = x[0:2, [3,4]]
print(z)

[[3 4]
 [8 9]]


In [88]:
print(x)
print('\n')
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[3 4]
 [8 9]]


In [95]:
z[1,1]=99
print(z)

[[ 3  4]
 [ 8 99]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [94]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [96]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [101]:
z = x[0:2, 3:].copy()
print(z)
z[1,1]=99
print(z)
print('\n')
print(x)

[[3 4]
 [8 9]]
[[ 3  4]
 [ 8 99]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Boolean Indexing

In [ ]:
import numpy as np

In [102]:
x = np.arange(50).reshape(5,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [103]:
y = x[x > 25]
print(y)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [104]:
print(x[x<=40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [105]:
print(x[(x>25 )& (x<30)])

[26 27 28 29]


In [106]:
x[(x>25 )& (x<30)] =666
print(x)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25 666 666 666 666]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


In [108]:
x = np.random.randint(1, 25, size=(100))
print(x)

[24 24 23  8  1 12  7 20  6  4  4  7  3 20  9  9  6 19 16 14 18  9 22 10
 18 14 15 11 20 24 23  8 21  7 11  8 19 18 10 16  8 15 13 13 14  4 20 18
 21 16  9 18  9 19  5  6  5 23 10  8 10 12  2 19  1  4 20 14 19  3 12  3
 16  4  5 19  1 11 16 14  7  2  9 16 13 18  3 15 11 13 22  3 24 21 13 20
  8  7 19 20]


In [109]:
print(x[x==20])

[20 20 20 20 20 20 20]


# Arithmetic Operations and Broadcasting

In [ ]:
import numpy as np

In [121]:
x = np.arange(4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)

print(x)
print('\n')
print(y)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


In [123]:
#Sum

print(x + y)
print(np.add(x,y))

[[ 4  6]
 [ 8 10]]
[[ 4  6]
 [ 8 10]]


In [124]:
#subtract

print(x - y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [125]:
#multiply

print(x * y)
print(np.multiply(x,y))

[[ 0  5]
 [12 21]]
[[ 0  5]
 [12 21]]


In [126]:
#divide

print(x / y)
print(np.divide(x,y))

[[0.         0.2       ]
 [0.33333333 0.42857143]]
[[0.         0.2       ]
 [0.33333333 0.42857143]]


In [127]:
#sqrt

print(np.sqrt(x))


[[0.         1.        ]
 [1.41421356 1.73205081]]


In [128]:
#exp

print(np.exp(x))

[[ 1.          2.71828183]
 [ 7.3890561  20.08553692]]


In [130]:
#power

print(np.power(x,2))

[[0 1]
 [4 9]]


In [132]:
# mean, std , median

print(x)
print('\n')
print(np.mean(x, axis=0))

[[0 1]
 [2 3]]


[1. 2.]


In [133]:
print(np.median(x))

1.5


In [134]:
print(np.max(x))

3


In [135]:
print(np.min(x))

0


In [136]:
#Broadcasting

x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [137]:
print(x + 4)

[[4 5]
 [6 7]]


In [138]:
y = np.array([7,8])
y

array([7, 8])

In [139]:
print(x + y)

[[ 7  9]
 [ 9 11]]
