In [3]:
def greetings():
    print ('Hello')

greetings()


Hello


In [9]:
def square_area(lado):
    return lado**2
square_area(1)

def circle_area(radio):
    pi = 3.1416
    return pi*radio**2
circle_area(4)

50.2656

In [10]:
def multiply(x):
    return x * 5

multiply(3)

25

In [12]:
multiply_lambda = lambda x: x * 5
multiply_lambda(3)


15

In [15]:
divisible = lambda x, y: x % y == 0
divisible(32, 5)

False

In [19]:
# filter, evaluar toda la lista y mostrar solo los que cumple la cn+ondición

numbers = [4,6,9,2]

def multiple_dos(x):
    return x % 2 == 0

list(filter(multiple_dos, numbers))
list(filter(lambda x: x % 2 == 0, numbers))



[4, 6, 2]

In [25]:
#map evalua uno a uno los elementos y retorna un objeto para cada posicion de ellos 

numbers = [4,6,9,2]

def multiple_dos(x):
    return x % 2 == 0

list(map(multiple_dos,numbers))

list(map(lambda x: x % 2 == 0, numbers))


[True, True, False, True]

In [28]:
things = ['Mary', 'food', 'laptop', 'Jose']

# filter

names = list(filter(lambda x: x[0].isupper(), things))
print(names)

# map

check_names = list(map(lambda x: x[0].isupper(), things))
print(check_names)

['Mary', 'Jose']
[True, False, False, True]


# Object-Oriented Programming


Class       Forma de empaquetar atributos y metodos, estudiantes animales

Object      Es una instancia Ejemplo una clase animales y un objeto sera perro

Attribute   Descropciones de una caracteristica, el color, peso, raza 

Method      Son acciones que un objeto o clase pueden usar, comer, correr, ladrar

In [37]:
class Worker:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
     #setters
    def set_salary(self,salary):
        self.salary= salary
    
    #getters
    def get_net_salary(self):
        return 0.9 * self.salary

        

In [38]:
worker_one = Worker('Juan', 40)
print(worker_one.name)
       

In [47]:
class Doctor(Worker):
    
    def __init__(self , name,age,especialidad):
        Worker.__init__(self,name,age)
        self.especialidad = especialidad
        
    def schedule_operation(self):
        if schedule_operation == 'cardiologo':
            return '8 am'
        elif sef.especialidad == 'neurologo':
            return '4 pm'
        else:
            return '12 pm'
        
    def get_net_salary(self):
        Worker.set_salary(self, 1000)
        
        if schedule_operation == 'cardiologo':
            return self.salary * 1.5
        elif sef.especialidad == 'neurologo':
            return self.salary * 2
        else:
            return self.salary
        


In [46]:
doctor = Doctor('Luis', 45, 'cardiologo')
print(doctor.age)

45


In [50]:
import numpy as np

#acceder

x = np.array([1,2,3,4])
print(x[0])
print(x[3])

print(x[-1])
print(x[-2])

1
4
4
3


In [51]:
x[0] = 30
x[-1] = 60

print(x)

[30  2  3  4]


In [55]:
x = np.array([[1,2,3,], [4,5,6]])
print(x[0,1])
x[0,1]  = 20

print(x)

2
[[ 1 20  3]
 [ 4  5  6]]


In [59]:
#delete

x = np.array([1,2,3,4])
x = np.delete(x,[0,3])

print(x)

[2 3]


In [63]:
x = np.array([[1,2,3,], [4,5,6]])

print(x)

x = np.delete(x, 0, axis = 1)
print(x)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [65]:
# append

x = np.array([1,2,3,4])
print(x)
x = np.append(x,5)
x = np.append(x,[6,7])
print(x)

[1 2 3 4]
[1 2 3 4 5 6 7]


In [66]:
x = np.array([[1,2,3,], [4,5,6]])
x = np.append(x,[[7,8,9],[10,11,12]])
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
# insert
x = np.array([1, 2, 3, 4])
print(x)
x = np.insert(x,2,5)
print(x)

[1 2 3 4]
[1 2 5 3 4]


In [69]:
x = np.array([[1,2,3,], [4,5,6]])
print (x)

x= np.insert(x, 1, 99, axis = 1)
print(x)



[[1 2 3]
 [4 5 6]]
[[ 1 99  2  3]
 [ 4 99  5  6]]


In [72]:
# vstack
x = np.array([1, 2,])
print(x)
y = np.array([[3,4], [5,6]])
print(y)

z = np.vstack((x,y))
print(z)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
